# digestdb
#
# After modifying this file check it using: http://lint.travis-ci.org/
#

language: python

python:
  - "3.5"

install:
  - "pip install --use-mirrors -r requirements.txt"

script:
  - make test
